version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: patroller_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patroller
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: